### ISSUE TITLE
fshader 着色器 365行 报错 implicit cast from "uint" to "bool"

### ISSUE THREAD

**Issue by Hanggansta** [AKGWSB/EzRT#1]

**Comment by Hanggansta** [comment]
重要性采样的 fragment shader  生成 d维度 的第i 个sobol 数的代码有编译问题

**Comment by AKGWSB** [comment]
以前用的是 AMD 的核显，最近换了 N 卡才发现这个问题。把 GLSL 编译版本提升到 430，并且在初始化的时候使用无符号整数（比如：114514u）进行数组的初始化。具体的改动可以查看：[https://github.com/AKGWSB/EzRT/commit/51cf8774aba1120858f41107a2a66047fb2a0bc7](https://github.com/AKGWSB/EzRT/commit/51cf8774aba1120858f41107a2a66047fb2a0bc7) 

最新的改动已经提交到主分支，它将和 release 中的可执行文件保持一致

**Comment by AKGWSB** [comment]
如果仅仅是 ` implicit cast from "uint" to "bool"` 可以将 `if((i & 1)) `改为 `if((i & 1)!=0)`

**Comment by Hanggansta** [comment]
多谢老兄问题解决了，你的教程帮助我很多。

**Comment by AKGWSB** [comment]
不客气~
